import type { Config } from 'tailwindcss';

export default {
  content: ['./src/app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        arabic: ['var(--font-arabic)', 'Cairo', 'Tajawal', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      colors: {
        primary: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
          950: '#022c22',
        },
        secondary: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
          950: '#451a03',
        },
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-border': 'var(--color-surface-border)',
        muted: '#6b7280',
        'muted-foreground': '#6b7280',
        foreground: '#1f2937',
        accent: 'var(--color-primary-500)',
        'accent-foreground': '#ffffff',
        destructive: {
          DEFAULT: 'var(--color-error)',
          foreground: '#ffffff',
        },
        border: 'var(--color-surface-border)',
        ring: 'var(--color-primary-500)',
        popover: '#ffffff',
        'popover-foreground': '#1f2937',
        input: 'var(--color-surface-border)',
        card: '#ffffff',
        'card-foreground': '#1f2937',
        error: 'var(--color-error)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
      },
      borderRadius: {
        lg: 'var(--radius-lg)',
        md: 'var(--radius-md)',
        sm: 'var(--radius-sm)',
      },
      boxShadow: {
        soft: 'var(--shadow-soft)',
        medium: 'var(--shadow-medium)',
      },
    },
  },
  plugins: [],
} satisfies Config;
